import { Injectable, Logger, NotFoundException } from '@nestjs/common';
import { InjectModel } from '@nestjs/mongoose';
import { Model } from 'mongoose';
import {
  Ticket,
  TicketDocument,
  TicketStatus,
  TicketPriority,
  TicketCategory,
} from '../../database/schemas/ticket.schema';
import {
  SystemEvent,
  SystemEventDocument,
} from '../../database/schemas/system-event.schema';
import { KafkaService } from '../../kafka/kafka.service';
import { KAFKA_TOPICS } from '../../kafka/kafka.constants';

export interface CreateTicketDto {
  title: string;
  description: string;
  priority?: TicketPriority;
  category: TicketCategory;
  affectedUserId?: string;
  affectedSystem?: string;
  reportedBy?: string;
  isAutoGenerated?: boolean;
  aiConfidenceScore?: number;
  aiMetadata?: Record<string, any>;
  tags?: string[];
}

@Injectable()
export class TicketingService {
  private readonly logger = new Logger(TicketingService.name);

  constructor(
    @InjectModel(Ticket.name) private ticketModel: Model<TicketDocument>,
    @InjectModel(SystemEvent.name) private systemEventModel: Model<SystemEventDocument>,
    private readonly kafkaService: KafkaService,
  ) {}

  async createTicket(dto: CreateTicketDto): Promise<TicketDocument> {
    const ticket = new this.ticketModel({
      ...dto,
      status: TicketStatus.OPEN,
      priority: dto.priority || TicketPriority.MEDIUM,
    });

    const saved = await ticket.save();

    await this.kafkaService.publish(KAFKA_TOPICS.TICKET_CREATED, {
      ticketId: saved._id.toString(),
      title: saved.title,
      priority: saved.priority,
      category: saved.category,
      isAutoGenerated: saved.isAutoGenerated,
    });

    this.logger.log(`Ticket created: ${saved._id} — ${saved.title}`);
    return saved;
  }

  async createFromSystemEvent(event: {
    type: string;
    severity: string;
    source: string;
    message: string;
    payload: Record<string, any>;
    aiConfidenceScore?: number;
  }): Promise<TicketDocument> {
    const priorityMap: Record<string, TicketPriority> = {
      critical: TicketPriority.CRITICAL,
      error: TicketPriority.HIGH,
      warning: TicketPriority.MEDIUM,
      info: TicketPriority.LOW,
    };

    const categoryMap: Record<string, TicketCategory> = {
      software_bug: TicketCategory.SOFTWARE,
      hardware_fault: TicketCategory.HARDWARE,
      performance: TicketCategory.SOFTWARE,
      security: TicketCategory.SOFTWARE,
    };

    const ticket = await this.createTicket({
      title: `[AI Detected] ${event.message}`,
      description: `Automatically detected by AI monitoring service.\n\nSource: ${event.source}\nType: ${event.type}\nDetails: ${JSON.stringify(event.payload, null, 2)}`,
      priority: priorityMap[event.severity] || TicketPriority.MEDIUM,
      category: categoryMap[event.type] || TicketCategory.AI_DETECTED,
      affectedSystem: event.source,
      isAutoGenerated: true,
      aiConfidenceScore: event.aiConfidenceScore,
      aiMetadata: event.payload,
      tags: ['ai-generated', event.type, event.severity],
    });

    await this.systemEventModel.findOneAndUpdate(
      { source: event.source, message: event.message, isProcessed: false },
      { $set: { isProcessed: true, ticketCreated: true, ticketId: ticket._id.toString() } },
    );

    return ticket;
  }

  async findAll(query: {
    status?: string;
    priority?: string;
    category?: string;
    page?: number;
    limit?: number;
  }) {
    const { status, priority, category, page = 1, limit = 20 } = query;
    const filter: any = {};
    if (status) filter.status = status;
    if (priority) filter.priority = priority;
    if (category) filter.category = category;

    const [tickets, total] = await Promise.all([
      this.ticketModel
        .find(filter)
        .skip((page - 1) * limit)
        .limit(limit)
        .sort({ createdAt: -1 })
        .exec(),
      this.ticketModel.countDocuments(filter),
    ]);

    return { data: tickets, total, page, limit };
  }

  async findById(id: string): Promise<TicketDocument> {
    const ticket = await this.ticketModel.findById(id).exec();
    if (!ticket) throw new NotFoundException(`Ticket ${id} not found`);
    return ticket;
  }

  async updateStatus(id: string, status: TicketStatus): Promise<TicketDocument> {
    const update: any = { status };
    if (status === TicketStatus.RESOLVED) update.resolvedAt = new Date();

    const ticket = await this.ticketModel.findByIdAndUpdate(id, { $set: update }, { new: true });
    if (!ticket) throw new NotFoundException(`Ticket ${id} not found`);
    return ticket;
  }

  async addComment(id: string, author: string, content: string): Promise<TicketDocument> {
    const ticket = await this.ticketModel.findByIdAndUpdate(
      id,
      { $push: { comments: { author, content, createdAt: new Date() } } },
      { new: true },
    );
    if (!ticket) throw new NotFoundException(`Ticket ${id} not found`);
    return ticket;
  }

  async getDashboardStats() {
    const [total, open, inProgress, resolved, critical, aiGenerated] = await Promise.all([
      this.ticketModel.countDocuments(),
      this.ticketModel.countDocuments({ status: TicketStatus.OPEN }),
      this.ticketModel.countDocuments({ status: TicketStatus.IN_PROGRESS }),
      this.ticketModel.countDocuments({ status: TicketStatus.RESOLVED }),
      this.ticketModel.countDocuments({ priority: TicketPriority.CRITICAL }),
      this.ticketModel.countDocuments({ isAutoGenerated: true }),
    ]);

    return { total, open, inProgress, resolved, critical, aiGenerated };
  }
}
