export interface User {
  _id: string;
  firstName: string;
  lastName: string;
  email: string;
  companyEmail?: string;
  role: string;
  department: string;
  jobTitle: string;
  status: 'active' | 'inactive' | 'pending' | 'suspended';
  employeeType: string;
  provisionedServices: string[];
  externalIds: Record<string, string>;
  createdAt: string;
}

export interface Integration {
  _id: string;
  provider: string;
  displayName: string;
  status: 'active' | 'inactive' | 'error' | 'configuring';
  isEnabled: boolean;
  lastSyncAt?: string;
  lastErrorMessage?: string;
  syncCount: number;
  errorCount: number;
}

export interface Ticket {
  _id: string;
  title: string;
  description: string;
  status: 'open' | 'in_progress' | 'pending' | 'resolved' | 'closed';
  priority: 'low' | 'medium' | 'high' | 'critical';
  category: string;
  reportedBy?: string;
  assignedTo?: string;
  affectedSystem?: string;
  isAutoGenerated: boolean;
  aiConfidenceScore?: number;
  tags: string[];
  createdAt: string;
}

export interface ProvisioningLog {
  _id: string;
  userId: string;
  userEmail: string;
  role: string;
  action: 'provision' | 'deprovision' | 'update' | 'retry';
  status: 'pending' | 'in_progress' | 'success' | 'failed' | 'partial';
  provider: string;
  externalId?: string;
  errorMessage?: string;
  retryCount: number;
  createdAt: string;
  completedAt?: string;
}

export interface PaginatedResponse<T> {
  data: T[];
  total: number;
  page: number;
  limit: number;
  totalPages?: number;
}
