export type TicketStatus = 'open' | 'in_progress' | 'pending' | 'resolved' | 'closed';
export type TicketPriority = 'low' | 'medium' | 'high' | 'critical';
export type TicketCategory =
  | 'software'
  | 'hardware'
  | 'access'
  | 'provisioning'
  | 'general'
  | 'ai_detected';

export interface TicketComment {
  author: string;
  content: string;
  createdAt: string;
}

export interface Ticket {
  _id: string;
  title: string;
  description: string;
  status: TicketStatus;
  priority: TicketPriority;
  category: TicketCategory;
  reportedBy?: string;
  assignedTo?: string;
  affectedUserId?: string;
  affectedSystem?: string;
  isAutoGenerated: boolean;
  aiConfidenceScore?: number;
  aiMetadata?: Record<string, any>;
  comments: TicketComment[];
  tags: string[];
  resolvedAt?: string;
  createdAt: string;
  updatedAt: string;
}

export interface CreateTicketPayload {
  title: string;
  description: string;
  priority?: TicketPriority;
  category: TicketCategory;
  affectedSystem?: string;
  reportedBy?: string;
  tags?: string[];
}

export interface TicketStats {
  total: number;
  open: number;
  inProgress: number;
  resolved: number;
  critical: number;
  aiGenerated: number;
}

export interface PaginatedTickets {
  data: Ticket[];
  total: number;
  page: number;
  limit: number;
}
