import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { Document } from 'mongoose';

export type TicketDocument = Ticket & Document;

export enum TicketStatus {
  OPEN = 'open',
  IN_PROGRESS = 'in_progress',
  PENDING = 'pending',
  RESOLVED = 'resolved',
  CLOSED = 'closed',
}

export enum TicketPriority {
  LOW = 'low',
  MEDIUM = 'medium',
  HIGH = 'high',
  CRITICAL = 'critical',
}

export enum TicketCategory {
  SOFTWARE = 'software',
  HARDWARE = 'hardware',
  ACCESS = 'access',
  PROVISIONING = 'provisioning',
  GENERAL = 'general',
  AI_DETECTED = 'ai_detected',
}

@Schema({ timestamps: true, collection: 'tickets' })
export class Ticket {
  @Prop({ required: true })
  title: string;

  @Prop({ required: true })
  description: string;

  @Prop({ enum: TicketStatus, default: TicketStatus.OPEN })
  status: TicketStatus;

  @Prop({ enum: TicketPriority, default: TicketPriority.MEDIUM })
  priority: TicketPriority;

  @Prop({ enum: TicketCategory, required: true })
  category: TicketCategory;

  @Prop()
  reportedBy: string;

  @Prop()
  assignedTo: string;

  @Prop()
  affectedUserId: string;

  @Prop()
  affectedSystem: string;

  @Prop({ default: false })
  isAutoGenerated: boolean;

  @Prop()
  aiConfidenceScore: number;

  @Prop({ type: Object, default: {} })
  aiMetadata: Record<string, any>;

  @Prop({ type: [Object], default: [] })
  comments: Array<{
    author: string;
    content: string;
    createdAt: Date;
  }>;

  @Prop({ type: [Object], default: [] })
  attachments: Array<{
    name: string;
    url: string;
    type: string;
  }>;

  @Prop()
  resolvedAt: Date;

  @Prop()
  dueDate: Date;

  @Prop({ type: [String], default: [] })
  tags: string[];

  @Prop({ type: Object, default: {} })
  metadata: Record<string, any>;
}

export const TicketSchema = SchemaFactory.createForClass(Ticket);

TicketSchema.index({ status: 1 });
TicketSchema.index({ priority: 1 });
TicketSchema.index({ category: 1 });
TicketSchema.index({ assignedTo: 1 });
TicketSchema.index({ createdAt: -1 });
